"""Create a small connected dataset for local or hosted GigSchool QA testing.

Run with GIGSCHOOL_SEED_PASSWORD set. The script reads Supabase credentials from
backend/.env and writes the resulting test login details to an ignored local file.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from supabase import Client, create_client


ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")

PASSWORD = os.environ.get("GIGSCHOOL_SEED_PASSWORD")
if not PASSWORD:
    raise SystemExit("Set GIGSCHOOL_SEED_PASSWORD before running this script.")

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

ACCOUNTS = [
    {
        "email": "maya.test@gigschool.local",
        "username": "Maya Rao",
        "bio": "UI/UX student designer who turns rough ideas into clear, friendly experiences.",
        "skills": ["Figma", "UI Design", "Branding"],
        "avatar_url": "https://api.dicebear.com/9.x/initials/svg?seed=Maya%20Rao",
    },
    {
        "email": "arjun.test@gigschool.local",
        "username": "Arjun Mehta",
        "bio": "Full-stack student developer focused on fast, accessible web apps.",
        "skills": ["React", "Python", "SQL"],
        "avatar_url": "https://api.dicebear.com/9.x/initials/svg?seed=Arjun%20Mehta",
    },
    {
        "email": "priya.test@gigschool.local",
        "username": "Priya Shah",
        "bio": "Peer tutor for mathematics and science with a practical, patient teaching style.",
        "skills": ["Mathematics", "Physics", "Tutoring"],
        "avatar_url": "https://api.dicebear.com/9.x/initials/svg?seed=Priya%20Shah",
    },
    {
        "email": "kabir.test@gigschool.local",
        "username": "Kabir Khan",
        "bio": "Student writer helping teams communicate with concise, useful content.",
        "skills": ["Writing", "Research", "Editing"],
        "avatar_url": "https://api.dicebear.com/9.x/initials/svg?seed=Kabir%20Khan",
    },
]


def profile_for(account: dict[str, Any]) -> dict[str, Any]:
    existing = supabase.table("users").select("id").eq("email", account["email"]).execute()
    if existing.data:
        return existing.data[0]

    created = supabase.auth.admin.create_user(
        {
            "email": account["email"],
            "password": PASSWORD,
            "email_confirm": True,
            "user_metadata": {"username": account["username"]},
        }
    )
    user_id = str(created.user.id)
    profile = {"id": user_id, **account, "metadata": {"seed": "gigschool-qa"}}
    supabase.table("users").insert(profile).execute()
    return {"id": user_id}


def insert_job(creator_id: str, **job: Any) -> dict[str, Any]:
    response = supabase.table("jobs").insert({"creator_id": creator_id, **job}).execute()
    return response.data[0]


def add_optional_portfolios(user_ids: dict[str, str]) -> None:
    items = [
        {"user_id": user_ids["Maya Rao"], "title": "Campus Event Posters", "description": "Poster system for student club events.", "link": "https://example.com/maya-posters", "file_type": "link"},
        {"user_id": user_ids["Arjun Mehta"], "title": "Study Group Finder", "description": "A small app for matching study partners.", "link": "https://example.com/arjun-study", "file_type": "link"},
    ]
    try:
        supabase.table("portfolio_items").insert(items).execute()
    except Exception as error:
        print(f"Portfolio seed skipped: {error}")


def write_account_notes() -> None:
    account_lines = "\n".join(f"| {a['username']} | {a['email']} | {PASSWORD} |" for a in ACCOUNTS)
    notes = f"""# GigSchool Test Accounts

Generated by `backend/scripts/seed_test_data.py`. This file is intentionally ignored by Git.

| User | Email | Password |
| --- | --- | --- |
{account_lines}

Use these accounts only for GigSchool QA and performance testing.
"""
    (ROOT / "TEST_ACCOUNTS.local.md").write_text(notes, encoding="ascii")


def main() -> None:
    profiles = {account["username"]: profile_for(account) for account in ACCOUNTS}
    user_ids = {name: profile["id"] for name, profile in profiles.items()}

    maya = user_ids["Maya Rao"]
    arjun = user_ids["Arjun Mehta"]
    priya = user_ids["Priya Shah"]
    kabir = user_ids["Kabir Khan"]

    jobs = [
        insert_job(maya, title="[TEST] Design a fresher orientation poster", description="Create a bright, readable poster for the first-year orientation event. Include a print-ready and social-media version.", tags=["figma", "poster", "branding"], category="design", group_id="college-design", resume_required=False, status="OPEN"),
        insert_job(maya, title="[TEST] Create Instagram templates for coding club", description="Design six reusable Instagram templates for workshop announcements and speaker cards.", tags=["social-media", "canva", "design"], category="design", group_id="college-design", resume_required=False, status="OPEN"),
        insert_job(arjun, title="[TEST] Build a simple attendance tracker", description="Need a lightweight React interface for recording weekly attendance and exporting a CSV.", tags=["react", "frontend", "csv"], category="coding", group_id="college-engineering", resume_required=True, status="OPEN"),
        insert_job(arjun, title="[TEST] Debug a Python data-cleaning script", description="Help identify why a pandas script is producing duplicate rows and improve its error messages.", tags=["python", "pandas", "debugging"], category="coding", group_id="college-engineering", resume_required=False, status="OPEN"),
        insert_job(priya, title="[TEST] Weekend calculus tutoring", description="Tutor a first-year student on limits, differentiation, and practice problem strategy.", tags=["calculus", "tutoring", "math"], category="tutoring", group_id="college-science", resume_required=False, status="OPEN"),
        insert_job(kabir, title="[TEST] Write descriptions for student marketplace listings", description="Write concise, trustworthy descriptions for ten student-made products.", tags=["writing", "copywriting", "editing"], category="writing", group_id="college-commerce", resume_required=False, status="OPEN"),
        insert_job(maya, title="[TEST] Completed: portfolio landing page design", description="Completed design sprint for a student portfolio landing page.", tags=["figma", "portfolio"], category="design", group_id="college-design", resume_required=False, status="COMPLETED"),
    ]

    applications = supabase.table("applications").insert([
        {"job_id": jobs[0]["id"], "applicant_id": arjun, "pitch": "I can turn the brief into a clean system and deliver both print and social variants.", "status": "PENDING"},
        {"job_id": jobs[1]["id"], "applicant_id": kabir, "pitch": "I have experience maintaining consistent tone across event posts and captions.", "status": "PENDING"},
        {"job_id": jobs[2]["id"], "applicant_id": priya, "pitch": "I can build the required interface and keep the workflow simple for coordinators.", "status": "ACCEPTED"},
        {"job_id": jobs[3]["id"], "applicant_id": maya, "pitch": "I can help test the workflow and make the output easier for non-technical users to understand.", "status": "PENDING"},
        {"job_id": jobs[4]["id"], "applicant_id": kabir, "pitch": "I am looking for a focused refresher before upcoming assessments.", "status": "PENDING"},
        {"job_id": jobs[5]["id"], "applicant_id": priya, "pitch": "I can write clear product descriptions and check them for grammar and consistency.", "status": "REJECTED"},
    ]).execute().data

    conversation = supabase.table("conversations").insert({"user1_id": maya, "user2_id": arjun}).execute().data[0]
    supabase.table("messages").insert([
        {"conversation_id": conversation["id"], "sender_id": maya, "content": "Hi Arjun, I liked your application for the orientation poster."},
        {"conversation_id": conversation["id"], "sender_id": arjun, "content": "Thanks Maya. I can share an initial visual direction tomorrow."},
        {"conversation_id": conversation["id"], "sender_id": maya, "content": "Great. Please keep the design readable from a distance."},
    ]).execute()

    supabase.table("bookmarks").insert([
        {"user_id": arjun, "job_id": jobs[0]["id"]},
        {"user_id": priya, "job_id": jobs[2]["id"]},
        {"user_id": kabir, "job_id": jobs[4]["id"]},
    ]).execute()
    supabase.table("reviews").insert([
        {"job_id": jobs[6]["id"], "reviewer_id": maya, "reviewee_id": arjun, "rating": 5, "comment": "Clear communication and thoughtful implementation throughout the project."},
        {"job_id": jobs[6]["id"], "reviewer_id": arjun, "reviewee_id": maya, "rating": 5, "comment": "The design brief was detailed and feedback was quick and helpful."},
    ]).execute()

    add_optional_portfolios(user_ids)
    write_account_notes()
    print(f"Seeded {len(profiles)} users, {len(jobs)} jobs, {len(applications)} applications, one conversation, bookmarks, reviews, and portfolios.")
    print("Credentials: backend/TEST_ACCOUNTS.local.md")


if __name__ == "__main__":
    main()
