"""Add a larger connected QA dataset to the configured GigSchool Supabase project."""

from __future__ import annotations

import os
from itertools import islice
from pathlib import Path
from typing import Any, Iterable

from dotenv import load_dotenv
from supabase import Client, create_client


ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")

PASSWORD = os.environ.get("GIGSCHOOL_SEED_PASSWORD")
if not PASSWORD:
    raise SystemExit("Set GIGSCHOOL_SEED_PASSWORD before running this script.")

supabase: Client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])

FIRST_NAMES = [
    "Aarav", "Ananya", "Dev", "Isha", "Rohan", "Nisha", "Vikram", "Meera", "Aditya", "Kavya",
    "Neil", "Tanya", "Rahul", "Simran", "Kiran", "Aditi", "Samar", "Diya", "Ibrahim", "Zoya",
]
CATEGORIES = ["coding", "design", "tutoring", "writing", "general"]
GROUPS = ["college-engineering", "college-design", "college-science", "college-commerce", "general"]
TEMPLATES = {
    "coding": ("Build a student event registration page", "Create a responsive page with a short registration form, validation, and confirmation state.", ["react", "frontend", "web"]),
    "design": ("Design social assets for a campus event", "Prepare a flexible visual system for a campus event with post and story formats.", ["figma", "branding", "social-media"]),
    "tutoring": ("Help with a focused exam revision session", "Run a focused one-hour revision session with worked examples and a short practice plan.", ["tutoring", "revision", "study"]),
    "writing": ("Edit student project documentation", "Improve clarity, structure, grammar, and readability for a student project document.", ["writing", "editing", "research"]),
    "general": ("Support a student club task", "Help a student club complete a clearly scoped task before its next event.", ["student-club", "planning", "communication"]),
}


def batches(items: list[dict[str, Any]], size: int = 50) -> Iterable[list[dict[str, Any]]]:
    iterator = iter(items)
    while batch := list(islice(iterator, size)):
        yield batch


def load_account(index: int, name: str) -> dict[str, Any]:
    email = f"load{index:02d}.test@gigschool.local"
    existing = supabase.table("users").select("id,email,username").eq("email", email).execute().data
    if existing:
        return existing[0]

    created = supabase.auth.admin.create_user(
        {
            "email": email,
            "password": PASSWORD,
            "email_confirm": True,
            "user_metadata": {"username": f"{name} Test"},
        }
    )
    profile = {
        "id": str(created.user.id),
        "email": email,
        "username": f"{name} Test",
        "bio": "Synthetic GigSchool QA account for marketplace and performance testing.",
        "skills": ["Communication", "Student Projects", "Collaboration"],
        "avatar_url": f"https://api.dicebear.com/9.x/initials/svg?seed={name}%20Test",
        "metadata": {"seed": "gigschool-load-test"},
    }
    supabase.table("users").insert(profile).execute()
    return {"id": profile["id"], "email": email, "username": profile["username"]}


def get_or_create_conversation(user1_id: str, user2_id: str) -> dict[str, Any]:
    direct = supabase.table("conversations").select("id").eq("user1_id", user1_id).eq("user2_id", user2_id).execute().data
    reverse = supabase.table("conversations").select("id").eq("user1_id", user2_id).eq("user2_id", user1_id).execute().data
    if direct:
        return direct[0]
    if reverse:
        return reverse[0]
    return supabase.table("conversations").insert({"user1_id": user1_id, "user2_id": user2_id}).execute().data[0]


def write_account_notes(accounts: list[dict[str, Any]]) -> None:
    rows = "\n".join(f"| {account['username']} | {account['email']} |" for account in accounts)
    notes = f"""# GigSchool Load-Test Accounts

Generated by `backend/scripts/seed_load_data.py`. This file is ignored by Git.

All accounts use this password: `{PASSWORD}`

| User | Email |\n| --- | --- |\n{rows}
"""
    (ROOT / "LOAD_TEST_ACCOUNTS.local.md").write_text(notes, encoding="ascii")


def main() -> None:
    accounts = [load_account(index, name) for index, name in enumerate(FIRST_NAMES, start=1)]
    account_ids = [account["id"] for account in accounts]

    jobs: list[dict[str, Any]] = []
    for index in range(100):
        category = CATEGORIES[index % len(CATEGORIES)]
        title, description, tags = TEMPLATES[category]
        jobs.append(
            {
                "creator_id": account_ids[index % len(account_ids)],
                "title": f"[TEST LOAD {index + 1:03d}] {title}",
                "description": f"{description} Test batch item {index + 1}.",
                "tags": tags,
                "category": category,
                "group_id": GROUPS[index % len(GROUPS)],
                "resume_required": index % 4 == 0,
                "status": "COMPLETED" if index % 10 == 0 else "CLOSED" if index % 10 == 1 else "OPEN",
                "payload": {"seed": "gigschool-load-test", "batch": 1, "sequence": index + 1},
            }
        )
    inserted_jobs: list[dict[str, Any]] = []
    for batch in batches(jobs):
        inserted_jobs.extend(supabase.table("jobs").insert(batch).execute().data)

    applications: list[dict[str, Any]] = []
    bookmarks: list[dict[str, Any]] = []
    reviews: list[dict[str, Any]] = []
    for index, job in enumerate(inserted_jobs):
        creator_id = job["creator_id"]
        applicants = [account_id for account_id in account_ids if account_id != creator_id]
        for offset in range(2):
            applicant_id = applicants[(index + offset) % len(applicants)]
            applications.append(
                {
                    "job_id": job["id"],
                    "applicant_id": applicant_id,
                    "pitch": f"[TEST LOAD] I am interested in this task and can complete the required work for item {index + 1}.",
                    "status": "ACCEPTED" if offset == 0 and index % 10 == 0 else "REJECTED" if offset == 1 and index % 7 == 0 else "PENDING",
                }
            )
        bookmarks.append({"user_id": applicants[index % len(applicants)], "job_id": job["id"]})
        if index % 10 == 0:
            reviewer_id = applicants[0]
            reviews.append(
                {
                    "job_id": job["id"],
                    "reviewer_id": reviewer_id,
                    "reviewee_id": creator_id,
                    "rating": 4 if index % 20 else 5,
                    "comment": "[TEST LOAD] Clear scope, reliable communication, and a smooth collaboration.",
                }
            )
    for collection, table_name in ((applications, "applications"), (bookmarks, "bookmarks"), (reviews, "reviews")):
        for batch in batches(collection):
            supabase.table(table_name).insert(batch).execute()

    messages: list[dict[str, Any]] = []
    for index in range(20):
        sender = accounts[index]
        recipient = accounts[(index + 1) % len(accounts)]
        conversation = get_or_create_conversation(sender["id"], recipient["id"])
        messages.extend(
            [
                {"conversation_id": conversation["id"], "sender_id": sender["id"], "content": f"[TEST LOAD] Hi, I have a question about batch item {index + 1}."},
                {"conversation_id": conversation["id"], "sender_id": recipient["id"], "content": "[TEST LOAD] Happy to help. Please share the detail you need."},
            ]
        )
    for batch in batches(messages):
        supabase.table("messages").insert(batch).execute()

    write_account_notes(accounts)
    print(
        f"Created {len(accounts)} accounts, {len(inserted_jobs)} jobs, {len(applications)} applications, "
        f"{len(bookmarks)} bookmarks, {len(reviews)} reviews, and {len(messages)} messages."
    )
    print("Credentials: backend/LOAD_TEST_ACCOUNTS.local.md")


if __name__ == "__main__":
    main()
